# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [20]:
import torch

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
tensor = torch.rand([7,7])
tensor, tensor.shape

(tensor([[0.4224, 0.1583, 0.7461, 0.9665, 0.9698, 0.2216, 0.8091],
         [0.0015, 0.9258, 0.4432, 0.6839, 0.4935, 0.4241, 0.3517],
         [0.0954, 0.1499, 0.3991, 0.3971, 0.3448, 0.5904, 0.6029],
         [0.8213, 0.6709, 0.7383, 0.5423, 0.9249, 0.0248, 0.1723],
         [0.1207, 0.4554, 0.5823, 0.7136, 0.2576, 0.8015, 0.3314],
         [0.2099, 0.0120, 0.6224, 0.5500, 0.7624, 0.6339, 0.8644],
         [0.9276, 0.4318, 0.6120, 0.2530, 0.5494, 0.7104, 0.7254]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
tensor_2 = torch.rand([1,7])

# Perform matrix multiplication 
tensor_mul = torch.matmul(tensor, tensor_2.T)
tensor_mul, tensor_mul.shape

(tensor([[1.2239],
         [2.0847],
         [1.9002],
         [0.9408],
         [1.5213],
         [1.3606],
         [0.8780]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED) 
# Create two random tensors
import torch
tensor = torch.rand([7,7])
tensor_2 = torch.rand([1,7])
# Matrix multiply tensors
tensor_mul = torch.matmul(tensor, tensor_2.T)
tensor_mul, tensor_mul.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU (torch.manual_seed() does both CPU and GPU)
RANDOM_SEED = 1234
torch.manual_seed(seed=RANDOM_SEED) 


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Check for access to GPU
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        device = torch.device('cpu')
else:
    # this ensures that the current MacOS version is at least 12.3+
    print(torch.backends.mps.is_available())
    # this ensures that the current current PyTorch installation was built with MPS activated.
    print(torch.backends.mps.is_built())
    device = torch.device('mps') 
    print("==>> device: ", device)
# Create two random tensors on GPU
tensor_A = torch.rand([2,3], device=device)
tensor_B = torch.rand([2,3], device=device)
tensor_A, tensor_B

True
True
==>> device:  mps


(tensor([[0.8956, 0.4592, 0.8060],
         [0.2350, 0.0150, 0.6553]], device='mps:0'),
 tensor([[0.9054, 0.8895, 0.7996],
         [0.7942, 0.9187, 0.1736]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.mm(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.5653, 0.0834],
         [0.8043, 0.8426]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [18]:

# Perform matmul on tensor_A and tensor_B
tensor_C = torch.mm(tensor_A, tensor_B.T)

# Find max
tensor_C_max = torch.max(tensor_C)

# Find min
tensor_C_min = torch.min(tensor_C)

tensor_C_max, tensor_C_min

(tensor(0.8426, device='mps:0'), tensor(0.0834, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
tensor_C_argmax = torch.argmax(tensor_C)

# Find arg min
tensor_C_argmin = torch.argmin(tensor_C)
tensor_C_argmax, tensor_C_argmin

(tensor(3, device='mps:0'), tensor(1, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
RANDOM_SEED = 1234
torch.manual_seed(seed=RANDOM_SEED)
# Create random tensor
tensor_X = torch.rand([1,1,1,10])
tensor_Y = torch.rand([1,1,1,10])
# Remove single dimensions
tensor_Y = torch.squeeze(tensor_Y)
# Print out tensors and their shapes
tensor_X, tensor_X.shape, tensor_Y, tensor_Y.shape

(tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
            0.6738, 0.3315]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.7837, 0.5631, 0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388,
         0.7313]),
 torch.Size([10]))